services:
  open-webui:
    container_name: open-webui
    build:
      context: ./open-webui
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./data/open-webui:/app/backend/data
    environment:
      WEBUI_SECRET_KEY: ""
      ENABLE_OLLAMA_API: "false"
      OPENAI_API_BASE_URL: "http://litellm:4000"
      OPENAI_API_KEY: "sk-12345"

      # Cognito 認証
      ENABLE_LOGIN_FORM: "false"
      ENABLE_OAUTH_SIGNUP: true
      WEBUI_URL: http://localhost:8080
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
      OPENID_PROVIDER_URL: ${OPENID_PROVIDER_URL}

      # # アプリケーションデータを保存するバケット
      # S3_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      # S3_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      # S3_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      # # S3_ENDPOINT_URL: 'https://s3.us-east-1.amazonaws.com'
      # S3_REGION_NAME: 'ap-northeast-1'
      # S3_BUCKET_NAME: open-webui-storage-660782280015-ap-northeast-1
      # デバッグ
      GLOBAL_LOG_LEVEL: DEBUG

  litellm:
    container_name: litellm
    build:
      context: ./litellm
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    # bedrockにアクセス権限のあるクレデンシャル情報
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      AWS_REGION_NAME: ${AWS_REGION}

  mcpo:
    container_name: mcpo
    build:
      context: ./mcpo
      dockerfile: Dockerfile
    ports:
      - 8000:8000
