services:
  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    volumes:
      - ./data/open-webui:/app/backend/data
    ports:
      - 8080:8080
    environment:
      WEBUI_SECRET_KEY: ""
      ENABLE_OLLAMA_API: "false"
      OPENAI_API_BASE_URL: "http://litellm:4000"
      OPENAI_API_KEY: "sk-12345"

  litellm:
    container_name: litellm
    build:
      context: ./litellm
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    # bedrockにアクセス権限のあるクレデンシャル情報
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      AWS_REGION_NAME: ${AWS_REGION}

  mcpo:
    container_name: mcpo
    build:
      context: ./mcpo
      dockerfile: Dockerfile
    ports:
      - 8000:8000
