model_list:
  - model_name: claude-4-sonnet
    litellm_params:
      model: bedrock/us.anthropic.claude-sonnet-4-20250514-v1:0
      aws_region_name: us-east-1

  # - model_name: claude-3-7-sonnet
  #   litellm_params:
  #     model: bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0
  #     aws_region_name: us-east-1
  # - model_name: claude-3-5-sonnet
  #   litellm_params:
  #     model: bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0
  #     aws_region_name: us-east-1
